name: todo_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # https://pub.dev/packages/flutter_bloc/install
  flutter_bloc: ^8.1.2
  # https://pub.dev/packages/http/install
  http: ^0.13.5
  # https://pub.dev/packages/get_it/install
  get_it: ^7.2.0
  # https://pub.dev/packages/go_router/install
  go_router: ^6.0.8
  # https://pub.dev/packages/intl/install
  intl: ^0.18.0
  # https://pub.dev/packages/freezed_annotation/install
  freezed_annotation: ^2.2.0
  # https://pub.dev/packages/json_annotation/install
  json_annotation: ^4.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # https://pub.dev/packages/freezed/install
  freezed: ^2.3.2
  # https://pub.dev/packages/json_serializable/install
  json_serializable: ^6.6.1
  # https://pub.dev/packages/build_runner/install
  build_runner: ^2.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
